# Generated by Django 5.0.6 on 2024-08-25 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionG', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField()),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=50)),
                ('tipo_genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comunidad.tipogenero')),
            ],
        ),
    ]
