# Generated by Django 5.0.6 on 2024-08-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0002_disciplina_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='mensaje',
            field=models.TextField(),
        ),
    ]
