# Generated by Django 5.0.6 on 2024-08-27 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0004_alter_publicacion_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_genero',
        ),
        migrations.DeleteModel(
            name='TipoGenero',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
